#include<iostream>
using namespace std;
int main(){
    int month,day;
    cout<<"Enter day";
    cin>>day;
    cout<<"Enter month";
    cin>>month;
    if(month==1){
        if(1<=day&&day<=31){
            cout<<"valid";
        }
        else{
            cout<<"invalid";
        }
    }
    if(month==2)
    {
        if(1<=day&&day<=29){
            cout<<"valid";
        }
        else{
            cout<<"invalid";
        }
    }
    if(month==3){
        if(1<=day&&day<=31){
            cout<<"valid";
        }
        else{
            cout<<"invalid";
        }
    }
    if(month==4){
        if(1<=day&&day<=30){
            cout<<"valid";
        }
        else{
            cout<<"invalid";
        }
    }
    if(month==5){
        if(1<=day&&day<=31){
            cout<<"valid";
        }
        else{
            cout<<"invalid";
        }
    }
    if(month==6){
        if(1<=day&&day<=30){
            cout<<"valid";
        }
        else{
            cout<<"invalid";
        }
    }
    if(month==7){
        if(1<=day&&day<=31){
            cout<<"valid";
        }
        else{
            cout<<"invalid";
        }
    }
    if(month==8){
        if(1<=day&&day<=31){
            cout<<"valid";
        }
        else{
            cout<<"invalid";
        }
    }
    if(month==9){
        if(1<=day&&day<=30){
            cout<<"valid";
        }
        else{
            cout<<"invalid";
        }
    }
    if(month==10){
        if(1<=day&&day<=31){
            cout<<"valid";
        }
        else{
            cout<<"invalid";
        }
    }
    if(month==11){
        if(1<=day&&day<=30){
            cout<<"valid";
        }
        else{
            cout<<"invalid";
        }
    }
    if(month==12){
        if(1<=day&&day<=31){
            cout<<"valid";
        }
        else{
            cout<<"invalid";
        }
    }

    return 0;
}